update path to assets, fix workflow to move CNAME

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -20,6 +20,9 @@ jobs:
       - name: Build project
         run: dx build --release --platform web
 
+      - name: Move CNAME file
+        run: mv ./target/dx/hemi/release/web/public/assets/CNAME ./target/dx/hemi/release/web/public/CNAME || echo "CNAME file not found"
+
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
